Yj
Royalsyj/StockTracker pull request #5
Opened 2021-04-03 06:17 UTC by Royalsyj

2021-04-05 15:19 UTC, YoongJH commented on anyhow.txt
> +ye anyhow
Wot this

2021-04-05 15:20 UTC, YoongJH commented on pystonks.py
> +### Added by YJ on 3 April 2021
No need this, git commit will contain the info in git blame

2021-04-05 15:21 UTC, YoongJH requested changes
- [ ] remove ``` pycache pyc``` file

2021-05-01 03:39 UTC, Royalsyj commented on pystonks.py
> +### Added by YJ on 3 April 2021
fien

2021-05-01 03:39 UTC, closed without merging